// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBOelq1XWQZRvjBd4H-vyi6EHkIRZaibA',
    appId: '1:162873999490:web:e7eb230bc6852e76f4349b',
    messagingSenderId: '162873999490',
    projectId: 'appp-d95cd',
    authDomain: 'appp-d95cd.firebaseapp.com',
    storageBucket: 'appp-d95cd.appspot.com',
    measurementId: 'G-G85V5DFDDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfFrR5-6yu3caGtSnGqeQvgIZBnle2s0U',
    appId: '1:162873999490:android:2f16f005f9e65f78f4349b',
    messagingSenderId: '162873999490',
    projectId: 'appp-d95cd',
    storageBucket: 'appp-d95cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLMnRMlAkPcRwEwQ2q_g1FDxbgkFjuCQ',
    appId: '1:162873999490:ios:a8b65fbdf8812035f4349b',
    messagingSenderId: '162873999490',
    projectId: 'appp-d95cd',
    storageBucket: 'appp-d95cd.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLMnRMlAkPcRwEwQ2q_g1FDxbgkFjuCQ',
    appId: '1:162873999490:ios:267d21481330c3a2f4349b',
    messagingSenderId: '162873999490',
    projectId: 'appp-d95cd',
    storageBucket: 'appp-d95cd.appspot.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
